### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by guillermohaad** [arka9901/LODISI#5]
tracking in WEB 
functions:
1- search drivers
2- calculate arrival time

![image](https://user-images.githubusercontent.com/12921805/139490678-ce1bc9e1-6b25-4a94-8c96-7cc3aa5202b0.png)
Actions:
Export:  take screenshot tracking
Shared: generate URL to share tracking to Broker

**Comment by arka9901** [comment]
This portion done after android tracking section

**Comment by guillermohaad** [comment]
UPDATE issues

![image](https://user-images.githubusercontent.com/12921805/141648477-ad99a968-46ff-4ce9-bb94-51b478640bcd.png)

**Comment by guillermohaad** [comment]
update screen

![image](https://user-images.githubusercontent.com/12921805/143461930-aafa1f27-9343-475e-ab83-7f49799608f0.png)

**Comment by guillermohaad** [comment]
solved
