### ISSUE TITLE
Register load payment by factoring 

### ISSUE THREAD

**Issue by guillermohaad** [arka9901/LODISI#6]
change Title = Factoring payment, textbox commision put write , remove net pay + commision for add val, only 2 Status = PAID and On Hold

CHECK
![image](https://user-images.githubusercontent.com/12921805/139452061-8fc50292-705c-4158-9a19-42c76e3f9f76.png)

Status
ON HOLD
PAID

**Comment by guillermohaad** [comment]
pending upload document PDF

**Comment by guillermohaad** [comment]
remove sign of %  check https://lodisi.com/admin/invoice
![image](https://user-images.githubusercontent.com/12921805/139864403-d02e4858-9d92-4307-bf55-7ebc4eb35c29.png)

**Comment by arka9901** [comment]
Solve

**Comment by guillermohaad** [comment]
solved
