### ISSUE TITLE
Reports

### ISSUE THREAD

**Issue by guillermohaad** [arka9901/LODISI#8]
report 1
![image](https://user-images.githubusercontent.com/12921805/139445713-18f89fef-9a93-4f54-8e85-74c60c5ba27d.png)
report 2
![image](https://user-images.githubusercontent.com/12921805/139104799-d8720148-5a61-4535-bdfd-9cc9b6ccd4ad.png)

**Comment by arka9901** [comment]
Done

**Comment by guillermohaad** [comment]
solved
